### ISSUE TITLE
Inkycal does not work with latest linux kernel update (6.6.20)

### ISSUE THREAD

**Issue by the-sim87** [aceinnolab/Inkycal#327]
**Describe the bug**
Since the latest kernel update to 6.6.20 inkycal stopped working, I get a GPIO error. There is a change in GPIO of the kernel:
https://forums.raspberrypi.com/viewtopic.php?t=361116&start=100#p2203689

**To Reproduce**
sudo apt-get dist-upgrade 
reboot

Raspberry Pi Zero 2:
 - OS: Raspberry Pi OS Lite 64 Bit, Debian 12 (Bookworm)

original traceback:
```sh
/home/user/Inkycal/venv/lib/python3.11/site-packages/gpiozero/devices.py:295: PinFactoryFallback: Falling back from lgpio: module 'lgpio' has no attribute 'SETBIASDISABLE'
  warnings.warn(
Traceback (most recent call last):
  File "/home/inkyuser/Inkycal/inkyrun.py", line 4, in <module>
    inky = Inkycal(render=True)  # Initialise Inkycal
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/inkycal/main.py", line 112, in init
    self.Display = Display(settings["model"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/inkycal/display/display.py", line 39, in __init
    driver = import_driver(epaper_model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/inkycal/display/display.py", line 16, in import_driver
    return import_module(f'inkycal.display.drivers.{model}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/inkyuser/Inkycal/inkycal/display/drivers/epd_7_in_5_v3_colour.py", line 32, in <module>
    from inkycal.display.drivers import epdconfig
  File "/home/inkyuser/Inkycal/inkycal/display/drivers/epdconfig.py", line 272, in <module>
    implementation = RaspberryPi()
                     ^^^^^^^^^^^^^ 
File "/home/inkyuser/Inkycal/inkycal/display/drivers/epdconfig.py", line 56, in init
    self.GPIOBUSYPIN = gpiozero.Button(self.BUSYPIN, pullup=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/devices.py", line 103, in call
    self = super().call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/inputdevices.py", line 412, in _init
    super().init(
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/mixins.py", line 417, in __init
    super().init(*args, **kwargs)
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/input_devices.py", line 168, in __init
    self.pin.when_changed = self.pinchanged
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/pins/__init.py", line 471, in <lambda>
    lambda self, value: self._set_when_changed(value),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/pins/pi.py", line 636, in _set_when_changed
    self._enable_event_detect()
  File "/home/inkyuser/Inkycal/venv/lib/python3.11/site-packages/gpiozero/pins/rpigpio.py", line 220, in _enable_event_detect
    GPIO.add_event_detect(
RuntimeError: Failed to add edge detection
```

**Comment by aceisace** [comment]
I've pushed the required changes in the `hotfix/327` branch. May I kindly ask you to run Inkycal via that branch _with_ the latest kernel? Once you can confirm it works, I will merge it into main.
```sh
cd ~/Inkycal
git pull
git checkout hotfix/327
source venv/bin/activate
python inky_run.py
```

This assumes you have SPI enabled in the latest kernel. Please use the latest kernel for this test.

**Comment by the-sim87** [comment]
Hi!
Does not work:
`user@pi-display:~/Inkycal $ cd ~/Inkycal
user@pi-display:~/Inkycal $ git pull
Already up to date.
user@pi-display:~/Inkycal $ git checkout hotfix/327
error: pathspec 'hotfix/327' did not match any file(s) known to git
user@pi-display:~/Inkycal $
`

**Comment by aceisace** [comment]
I've adapted the README instructions so that new users do not attempt to use the latest version. With a link to the last supported version of Raspberry Pi OS and a warning that the latest version will not work, this should be complete, at least for now. Thanks for reporting this @the-sim87 !
